name: Build Docker and Upload to Release

on:
  push:
    branches:
      - master
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image and save to file
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t hbuilderx:${GITHUB_REF_NAME} \
            --output type=docker,dest=./hbuilderx.tar .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: hbuilderx-image
          path: ./hbuilderx.tar

  release:
    needs: build
    if: github.event_name == 'push' && (startsWith(github.ref, 'refs/tags/v'))
    runs-on: ubuntu-latest
    steps:
      - name: Download built image
        uses: actions/download-artifact@v4
        with:
          name: hbuilderx-image
          path: .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./hbuilderx.tar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
